/* Datos del comparador de palas de pádel.
   Edita o regenera este archivo (p. ej. con un scraper) y la web se actualiza.
   Estructura de cada producto documentada en el README. */
window.PRODUCTOS = [
  {
    "id": "bullpadel-vertex-04",
    "nombre": "Bullpadel Vertex 04",
    "marca": "Bullpadel",
    "precio": 289.95,
    "precioOriginal": 360,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "diamante",
    "balance": "alto",
    "peso": "360-375 g",
    "material": {
      "cara": "Carbono Xtend 12K",
      "nucleo": "MultiEVA"
    },
    "descripcion": "Pala de máxima potencia con forma de diamante y balance alto. Pensada para jugadores agresivos que buscan remates definitivos.",
    "valoracion": 4.7,
    "popularidad": 95,
    "url": "https://www.padelnuestro.com/bullpadel-vertex-04",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "bullpadel-hack-04",
    "nombre": "Bullpadel Hack 04",
    "marca": "Bullpadel",
    "precio": 259.95,
    "precioOriginal": 330,
    "nivel": "avanzado",
    "estilo": "polivalente",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "360-375 g",
    "material": {
      "cara": "Carbono Xtend 3K",
      "nucleo": "MultiEVA"
    },
    "descripcion": "Versión polivalente de la familia Hack: potencia con buen control y un punto dulce amplio. La pala de Paquito Navarro.",
    "valoracion": 4.6,
    "popularidad": 92,
    "url": "https://www.padelnuestro.com/bullpadel-hack-04",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "adidas-metalbone-3-3",
    "nombre": "Adidas Metalbone 3.3",
    "marca": "Adidas",
    "precio": 244.95,
    "precioOriginal": 380,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "diamante",
    "balance": "alto",
    "peso": "360-370 g",
    "material": {
      "cara": "Carbon Aluminized",
      "nucleo": "EVA Soft Performance"
    },
    "descripcion": "La pala de Ale Galán. Diamante de balance alto con superficie rugosa para máximo efecto y potencia en el remate.",
    "valoracion": 4.6,
    "popularidad": 90,
    "url": "https://www.padelmarket.com/adidas-metalbone-3-3",
    "tienda": "Padel Market",
    "anio": 2024
  },
  {
    "id": "nox-at10-genius-18k",
    "nombre": "Nox AT10 Genius 18K",
    "marca": "Nox",
    "precio": 219.95,
    "precioOriginal": 300,
    "nivel": "avanzado",
    "estilo": "polivalente",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "355-370 g",
    "material": {
      "cara": "Carbono 18K",
      "nucleo": "HR3 Black EVA"
    },
    "descripcion": "La pala de Agustín Tapia. Forma de lágrima polivalente con un equilibrio excelente entre control y pegada.",
    "valoracion": 4.8,
    "popularidad": 97,
    "url": "https://www.padelnuestro.com/nox-at10-genius-18k",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "head-speed-motion",
    "nombre": "Head Speed Motion",
    "marca": "Head",
    "precio": 129.95,
    "precioOriginal": 190,
    "nivel": "intermedio",
    "estilo": "polivalente",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "355-370 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "Tubular Spiral Tech"
    },
    "descripcion": "Polivalente cómoda y tolerante para jugadores intermedios que quieren progresar sin renunciar a algo de potencia.",
    "valoracion": 4.4,
    "popularidad": 80,
    "url": "https://www.padelmarket.com/head-speed-motion",
    "tienda": "Padel Market",
    "anio": 2023
  },
  {
    "id": "head-delta-motion",
    "nombre": "Head Delta Motion",
    "marca": "Head",
    "precio": 139.95,
    "precioOriginal": 200,
    "nivel": "intermedio",
    "estilo": "control",
    "forma": "diamante",
    "balance": "medio",
    "peso": "360-370 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "Power Foam"
    },
    "descripcion": "Forma diamante accesible: ofrece pegada con un control sorprendente para su categoría. Ideal para dar el salto al diamante.",
    "valoracion": 4.3,
    "popularidad": 76,
    "url": "https://www.padelnuestro.com/head-delta-motion",
    "tienda": "Padel Nuestro",
    "anio": 2023
  },
  {
    "id": "babolat-technical-viper",
    "nombre": "Babolat Technical Viper",
    "marca": "Babolat",
    "precio": 264.95,
    "precioOriginal": 350,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "diamante",
    "balance": "alto",
    "peso": "360-375 g",
    "material": {
      "cara": "Carbon Flax",
      "nucleo": "Black EVA Ultra"
    },
    "descripcion": "La pala de Juan Lebrón. Diamante puro de competición con tacto seco y máxima transmisión de potencia.",
    "valoracion": 4.5,
    "popularidad": 85,
    "url": "https://www.padelmarket.com/babolat-technical-viper",
    "tienda": "Padel Market",
    "anio": 2024
  },
  {
    "id": "babolat-air-veron",
    "nombre": "Babolat Air Veron",
    "marca": "Babolat",
    "precio": 174.95,
    "precioOriginal": 240,
    "nivel": "intermedio",
    "estilo": "polivalente",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "350-365 g",
    "material": {
      "cara": "Carbono",
      "nucleo": "X-EVA"
    },
    "descripcion": "Pala ligera y manejable de la familia Veron. Muy equilibrada, perfecta para jugadores que priorizan el manejo.",
    "valoracion": 4.4,
    "popularidad": 78,
    "url": "https://www.padelnuestro.com/babolat-air-veron",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "siux-electra-st3-stupa",
    "nombre": "Siux Electra ST3 Stupa",
    "marca": "Siux",
    "precio": 199.95,
    "precioOriginal": 290,
    "nivel": "avanzado",
    "estilo": "control",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "355-370 g",
    "material": {
      "cara": "Carbono 3K",
      "nucleo": "Black EVA"
    },
    "descripcion": "La pala de Fede Chingotto. Redonda de control con balance bajo, punto dulce enorme y salida de bola muy precisa.",
    "valoracion": 4.7,
    "popularidad": 88,
    "url": "https://www.padelmarket.com/siux-electra-st3-stupa",
    "tienda": "Padel Market",
    "anio": 2024
  },
  {
    "id": "starvie-raptor-pro",
    "nombre": "StarVie Raptor Pro",
    "marca": "StarVie",
    "precio": 209.95,
    "precioOriginal": 295,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "diamante",
    "balance": "alto",
    "peso": "360-375 g",
    "material": {
      "cara": "Carbono Aluminizado",
      "nucleo": "Energy Tech EVA"
    },
    "descripcion": "Diamante de altas prestaciones con superficie rugosa. Potencia y efectos para el jugador ofensivo de máximo nivel.",
    "valoracion": 4.4,
    "popularidad": 72,
    "url": "https://www.padelnuestro.com/starvie-raptor-pro",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "wilson-bela-pro-v3",
    "nombre": "Wilson Bela Pro v3",
    "marca": "Wilson",
    "precio": 189.95,
    "precioOriginal": 270,
    "nivel": "avanzado",
    "estilo": "control",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "355-365 g",
    "material": {
      "cara": "Carbono",
      "nucleo": "EVA Soft"
    },
    "descripcion": "Inspirada en Fernando Belasteguín. Redonda de control puro, muy cómoda y con un punto dulce centrado y amplio.",
    "valoracion": 4.5,
    "popularidad": 70,
    "url": "https://www.padelmarket.com/wilson-bela-pro-v3",
    "tienda": "Padel Market",
    "anio": 2023
  },
  {
    "id": "dunlop-aero-star-pro",
    "nombre": "Dunlop Aero-Star Pro",
    "marca": "Dunlop",
    "precio": 169.95,
    "precioOriginal": 250,
    "nivel": "intermedio",
    "estilo": "polivalente",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "360-370 g",
    "material": {
      "cara": "Carbono",
      "nucleo": "HD Comfort EVA"
    },
    "descripcion": "Lágrima polivalente con buen aguante aerodinámico. Equilibrio entre potencia y control para el jugador intermedio-avanzado.",
    "valoracion": 4.2,
    "popularidad": 64,
    "url": "https://www.padelnuestro.com/dunlop-aero-star-pro",
    "tienda": "Padel Nuestro",
    "anio": 2023
  },
  {
    "id": "nox-ml10-pro-cup",
    "nombre": "Nox ML10 Pro Cup",
    "marca": "Nox",
    "precio": 119.95,
    "precioOriginal": 170,
    "nivel": "intermedio",
    "estilo": "polivalente",
    "forma": "redonda",
    "balance": "medio",
    "peso": "360-375 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "HR3 EVA"
    },
    "descripcion": "Un clásico superventas. Redonda polivalente, fiable y duradera, perfecta para quien busca relación calidad-precio.",
    "valoracion": 4.5,
    "popularidad": 91,
    "url": "https://www.padelmarket.com/nox-ml10-pro-cup",
    "tienda": "Padel Market",
    "anio": 2023
  },
  {
    "id": "head-evo-speed",
    "nombre": "Head Evo Speed",
    "marca": "Head",
    "precio": 74.95,
    "precioOriginal": 110,
    "nivel": "iniciación",
    "estilo": "control",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "355-370 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "EVA Soft"
    },
    "descripcion": "Pala de iniciación cómoda y tolerante. Forma redonda con balance bajo para máximo control y mínimo riesgo de lesión.",
    "valoracion": 4.3,
    "popularidad": 82,
    "url": "https://www.padelnuestro.com/head-evo-speed",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "kuikma-pr-990-power",
    "nombre": "Kuikma PR 990 Power Hybrid",
    "marca": "Kuikma",
    "precio": 159.99,
    "precioOriginal": 180,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "diamante",
    "balance": "alto",
    "peso": "360-375 g",
    "material": {
      "cara": "Carbono 12K",
      "nucleo": "Black EVA"
    },
    "descripcion": "La gama alta de Decathlon. Diamante de potencia con acabado de carbono y una relación prestaciones-precio difícil de igualar.",
    "valoracion": 4.6,
    "popularidad": 84,
    "url": "https://www.decathlon.es/es/p/kuikma-pr-990-power-hybrid",
    "tienda": "Decathlon",
    "anio": 2024
  },
  {
    "id": "kuikma-pr-990-control",
    "nombre": "Kuikma PR 990 Control Soft",
    "marca": "Kuikma",
    "precio": 159.99,
    "precioOriginal": 180,
    "nivel": "avanzado",
    "estilo": "control",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "355-370 g",
    "material": {
      "cara": "Carbono 12K",
      "nucleo": "Soft EVA"
    },
    "descripcion": "Versión control de la gama PR 990: redonda, balance bajo y tacto blando para un toque preciso y cómodo.",
    "valoracion": 4.5,
    "popularidad": 79,
    "url": "https://www.decathlon.es/es/p/kuikma-pr-990-control-soft",
    "tienda": "Decathlon",
    "anio": 2024
  },
  {
    "id": "kuikma-pr-560-soft",
    "nombre": "Kuikma PR 560 Soft",
    "marca": "Kuikma",
    "precio": 79.99,
    "precioOriginal": 90,
    "nivel": "intermedio",
    "estilo": "control",
    "forma": "redonda",
    "balance": "medio",
    "peso": "360-370 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "Soft EVA"
    },
    "descripcion": "Pala intermedia muy equilibrada y asequible. Forma redonda con tacto cómodo, ideal para consolidar técnica.",
    "valoracion": 4.4,
    "popularidad": 86,
    "url": "https://www.decathlon.es/es/p/kuikma-pr-560-soft",
    "tienda": "Decathlon",
    "anio": 2024
  },
  {
    "id": "kuikma-pr-100",
    "nombre": "Kuikma PR 100",
    "marca": "Kuikma",
    "precio": 39.99,
    "nivel": "iniciación",
    "estilo": "control",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "360-375 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "FOAM"
    },
    "descripcion": "La pala de iniciación más vendida de Decathlon. Económica, tolerante y perfecta para los primeros partidos.",
    "valoracion": 4.2,
    "popularidad": 93,
    "url": "https://www.decathlon.es/es/p/kuikma-pr-100",
    "tienda": "Decathlon",
    "anio": 2024
  },
  {
    "id": "bullpadel-vertex-04-comfort",
    "nombre": "Bullpadel Vertex 04 Comfort",
    "marca": "Bullpadel",
    "precio": 269.95,
    "precioOriginal": 340,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "350-365 g",
    "material": {
      "cara": "Carbono Xtend 12K",
      "nucleo": "MultiEVA Soft"
    },
    "descripcion": "Variante Comfort del Vertex: misma potencia pero con tacto más blando y balance medio para reducir vibraciones.",
    "valoracion": 4.5,
    "popularidad": 74,
    "url": "https://www.padelnuestro.com/bullpadel-vertex-04-comfort",
    "tienda": "Padel Nuestro",
    "anio": 2024
  },
  {
    "id": "adidas-rx-series-light",
    "nombre": "Adidas RX Series Light",
    "marca": "Adidas",
    "precio": 89.95,
    "precioOriginal": 130,
    "nivel": "iniciación",
    "estilo": "polivalente",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "350-360 g",
    "material": {
      "cara": "Fibra de vidrio",
      "nucleo": "EVA Soft Performance"
    },
    "descripcion": "Pala ligera de iniciación-intermedio. Manejable y cómoda, buena para jugadores que empiezan o priorizan el manejo.",
    "valoracion": 4.1,
    "popularidad": 68,
    "url": "https://www.padelmarket.com/adidas-rx-series-light",
    "tienda": "Padel Market",
    "anio": 2023
  },
  {
    "id": "siux-pegasus-control",
    "nombre": "Siux Pegasus Control",
    "marca": "Siux",
    "precio": 109.95,
    "precioOriginal": 160,
    "nivel": "intermedio",
    "estilo": "control",
    "forma": "redonda",
    "balance": "bajo",
    "peso": "355-370 g",
    "material": {
      "cara": "Carbono 3K",
      "nucleo": "Black EVA"
    },
    "descripcion": "Redonda de control para intermedios. Punto dulce amplio y comportamiento muy noble en defensa y volea.",
    "valoracion": 4.3,
    "popularidad": 65,
    "url": "https://www.padelnuestro.com/siux-pegasus-control",
    "tienda": "Padel Nuestro",
    "anio": 2023
  },
  {
    "id": "wilson-blade-team",
    "nombre": "Wilson Blade Team v2",
    "marca": "Wilson",
    "precio": 99.95,
    "precioOriginal": 150,
    "nivel": "intermedio",
    "estilo": "polivalente",
    "forma": "lágrima",
    "balance": "medio",
    "peso": "360-370 g",
    "material": {
      "cara": "Fibra de carbono basalt",
      "nucleo": "EVA"
    },
    "descripcion": "Lágrima polivalente de gama media. Buen equilibrio general y acabado cuidado a un precio competitivo.",
    "valoracion": 4.2,
    "popularidad": 60,
    "url": "https://www.padelmarket.com/wilson-blade-team-v2",
    "tienda": "Padel Market",
    "anio": 2023
  },
  {
    "id": "nox-at10-luxury-genius",
    "nombre": "Nox AT10 Luxury Genius 12K",
    "marca": "Nox",
    "precio": 234.95,
    "precioOriginal": 320,
    "nivel": "avanzado",
    "estilo": "potencia",
    "forma": "lágrima",
    "balance": "alto",
    "peso": "360-375 g",
    "material": {
      "cara": "Carbono 12K",
      "nucleo": "HR3 EVA"
    },
    "descripcion": "Versión más potente del AT10 de Tapia, con balance alto. Para el jugador avanzado que busca un plus de pegada manteniendo control.",
    "valoracion": 4.6,
    "popularidad": 81,
    "url": "https://www.padelnuestro.com/nox-at10-luxury-genius-12k",
    "tienda": "Padel Nuestro",
    "anio": 2024
  }
];
